### ISSUE TITLE
[Bug] message send json bug

### ISSUE THREAD

**Issue by VictorZZH** [emqx/MQTTX#1366]
#### What did I do

just tried to send some message as usual for testing and get this error (after update to v1.9.4), see attached figure, seems to be  "\" JSON.parse bug.

#### Environment
- OS: Windows x64
- MQTTX v1.9.4

#### More detail
this is v1.9.4(bug version)
![v1 9 4](https://github.com/emqx/MQTTX/assets/85718161/e557e8e4-5b3a-4e57-ac60-6fe3d89b6864)

and this is v1.9.3
![v1 9 3](https://github.com/emqx/MQTTX/assets/85718161/f92c766e-01eb-4bc6-a77f-8659a7b16db3)

**Comment by ni00** [comment]
Hello @VictorZZH , thank you for your feedback. I have fixed this bug in this [PR: fix text processing error](https://github.com/emqx/MQTTX/pull/1359) and it will be released in the next version (1.9.5) of MQTTX.

**Comment by ysfscream** [comment]
Thanks for your feedback!

Welcome to try the new MQTTX release at https://github.com/emqx/MQTTX/releases/tag/v1.9.5. If problems persist, please let us know, and we will quickly address them.
