### ISSUE TITLE
The latest win version(1.4.0) can not connect to mqtt server

### ISSUE THREAD

**Issue by xuanwubing** [emqx/MQTTX#355]
the host input text can not be parsed. it's always 127.0.0.1.

**Comment by ysfscream** [comment]
OK, this is a bug, I will notify you after fixing it as soon as possible.

**Comment by ysfscream** [comment]
Thank you for your report. I have fixed this. Please download the v1.4.0 package again.

**Comment by shishirong** [comment]
@ysfscream  The latest version(1.4.0) on windows still have the bug,how to fix please?

**Comment by ysfscream** [comment]
@shishirong Have you downloaded the installation package again?

**Comment by shishirong** [comment]
> @shishirong Have you downloaded the installation package again?

It's resolved after download and install v1.4.0 from github release。The error version executable file is downloaded from [https://mqttx.app/](https://mqttx.app/), binary is different whith github release file。

**Comment by ysfscream** [comment]
@shishirong OK, Sorry to trouble you. But I tested it on https://mqttx.app, it seems there is no problem. Anyway, I will release a new version soon to completely solve this problem. thanks.

**Comment by ysfscream** [comment]
It has been fixed in [v1.4.1](https://github.com/emqx/MQTTX/releases/tag/v1.4.1), I will close this issue.
